version: '3'
 
services:
  haproxy:
    build: .
    restart: always
    ports:
      - 25565:25565
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy_minecraft.lua:/usr/local/etc/haproxy/haproxy_minecraft.lua
